<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\USER;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
public function run(): void
{
    USER::insert([
        [
            'name' => 'bassma',
            'access_code' => 'ADMIN1',
            'password' => Hash::make('123456'),
            'role' => 'admin',
            'device_id' => null,
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'aya',
            'access_code' => 'CB100',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-001',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'kaoutar',
            'access_code' => 'CB10',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-002',
            'is_active' => 0,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'omar',
            'access_code' => 'STU-1003',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-003',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'maroua',
            'access_code' => 'CB101',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-004',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'youssef',
            'access_code' => 'CB102',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-005',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'salma',
            'access_code' => 'CB103',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-006',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'hamza',
            'access_code' => 'CB104',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-007',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'nadia',
            'access_code' => 'CB105',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-008',
            'is_active' => 0,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'tariq',
            'access_code' => 'CB106',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-009',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'zineb',
            'access_code' => 'CB107',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-010',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'amine',
            'access_code' => 'CB108',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-011',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'hind',
            'access_code' => 'CB109',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-012',
            'is_active' => 0,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'rachid',
            'access_code' => 'CB110',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-013',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'samira',
            'access_code' => 'CB111',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-014',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'bilal',
            'access_code' => 'CB112',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-015',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'sara',
            'access_code' => 'CB113',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-016',
            'is_active' => 0,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'khalid',
            'access_code' => 'CB114',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-017',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'meriem',
            'access_code' => 'CB115',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-018',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'adam',
            'access_code' => 'CB116',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-019',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'imane',
            'access_code' => 'CB117',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-020',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'soufiane',
            'access_code' => 'CB118',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-021',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'hajar',
            'access_code' => 'CB119',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-022',
            'is_active' => 0,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'ilyas',
            'access_code' => 'CB120',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-023',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'fatima',
            'access_code' => 'CB121',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-024',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
    ],
    [
        'name' => 'mehdi',
        'access_code' => 'CB122',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-025',
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'yasmine',
        'access_code' => 'CB123',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-026',
        'is_active' => 0,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'anis',
        'access_code' => 'CB124',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-027',
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'nour',
        'access_code' => 'CB125',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-028',
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'karim',
        'access_code' => 'CB126',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-029',
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'malak',
        'access_code' => 'CB127',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-030',
        'is_active' => 0,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'ayoub',
        'access_code' => 'CB128',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-031',
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'doaa',
        'access_code' => 'CB129',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-032',
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'walid',
        'access_code' => 'CB130',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-033',
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'chaimae',
        'access_code' => 'CB131',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-034',
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'zakaria',
        'access_code' => 'CB132',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-035',
        'is_active' => 0,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'asmaa',
        'access_code' => 'CB133',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-036',
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'hamid',
        'access_code' => 'CB134',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-037',
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'ibtissam',
        'access_code' => 'CB135',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-038',
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'othmane',
        'access_code' => 'CB136',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-039',
        'is_active' => 0,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'salim',
        'access_code' => 'CB137',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-040',
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'nabila',
        'access_code' => 'CB138',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-041',
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'reda',
        'access_code' => 'CB139',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-042',
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'jamila',
        'access_code' => 'CB140',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-043',
        'is_active' => 0,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'mounir',
        'access_code' => 'CB141',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-044',
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'khadija',
        'access_code' => 'CB142',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-045',
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'brahim',
        'access_code' => 'CB143',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-046',
        'is_active' => 0,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'siham',
        'access_code' => 'CB144',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-047',
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'tarik',
        'access_code' => 'CB145',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-048',
        'is_active' => 1,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'nadia',
        'access_code' => 'CB146',
        'password' => Hash::make('123456'),
        'role' => 'student',
        'device_id' => 'DEV-049',
        'is_active' => 0,
        'created_at' => now(),
        'updated_at' => now(),
    ],
        [
            'name' => 'soumaya',
            'access_code' => 'CB147',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-050',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'yahya',
            'access_code' => 'CB148',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-051',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'iman',
            'access_code' => 'CB149',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-052',
            'is_active' => 0,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'hamidou',
            'access_code' => 'CB150',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-053',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'salim',
            'access_code' => 'CB151',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-054',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'hanane',
            'access_code' => 'CB152',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-055',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'ayman',
            'access_code' => 'CB153',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-056',
            'is_active' => 0,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'nadia2',
            'access_code' => 'CB154',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-057',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'ismail',
            'access_code' => 'CB155',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-058',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'meryem',
            'access_code' => 'CB156',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-059',
            'is_active' => 0,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'sami',
            'access_code' => 'CB157',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-060',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'hasna',
            'access_code' => 'CB158',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-061',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'jalal',
            'access_code' => 'CB159',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-062',
            'is_active' => 0,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'amal',
            'access_code' => 'CB160',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-063',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'abdelilah',
            'access_code' => 'CB161',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-064',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'soukaina',
            'access_code' => 'CB162',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-065',
            'is_active' => 0,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'achraf',
            'access_code' => 'CB163',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-066',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'ikram',
            'access_code' => 'CB164',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-067',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'hamza2',
            'access_code' => 'CB165',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-068',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'rahma',
            'access_code' => 'CB166',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-069',
            'is_active' => 0,
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'name' => 'badr',
            'access_code' => 'CB167',
            'password' => Hash::make('123456'),
            'role' => 'student',
            'device_id' => 'DEV-070',
            'is_active' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ],
    ]);
}
}